version: "3.8"

services:
  db:
    image:  postgres:15
    container_name: todo_db
    restart:  always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
      - ./migrations:/

volumes:
  postgres_data:

  